### ISSUE TITLE
Tokens doesn't seem to be saved ??

### ISSUE THREAD

**Issue by stonerrb** [stonerrb/Task-App-Course3#2]
#So, when just keeping/ making a token, and the trying to login, it works perfectly, Output looks like this..
{
    "user": {
        "_id": "6435677a9de631ba1aa36a7f",
        "name": "Tanish",
        "email": "tpn@gmail.com",
        "age": 0,
        "password": "$2a$08$.n4T4b79TWATwfGnuEfokeAoIuxLsa5v8NjAyPpM.XSFpfTEKBNrm",
        "tokens": [],
        "__v": 0
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDM1Njc3YTlkZTYzMWJhMWFhMzZhN2YiLCJpYXQiOjE2ODEyMjIxNzh9.yaY_e5jr-kUxdfSPUg0cWvwSenuGviuYuUWAJaHNplg"
}

#Then we add a way to save the token for future logging in, the code to this is.
userSchema.methods.generateAuthToken = async function (){
    const user = this
    const token = jwt.sign({ _id: user._id.toString() }, 'isthisthetoken')

    user.tokens = user.token.concat({ token })
    await user.save()

    // console.log(token)
    return token
}
#This is the code to generate and save the AuthToken, so now when you run login, the output is an empty document.

**Comment by soumil4561** [comment]
hey yall

**Comment by stonerrb** [comment]
Ok, definitely some typo's in this code, did the same for my other project ( Gourmet - backend ) and it works perfectly, with sessions storing and , logout clearing.

**Comment by soumil4561** [comment]
hmm, could be. Looking into it
